module _ // Auto generated by https://github.com/bwplotka/bingo. DO NOT EDIT

go 1.15

// TODO(onprem): Migrate to github.com/observatorium/api after a tagged release
require github.com/observatorium/observatorium v0.1.1
