module _ // Auto generated by https://github.com/bwplotka/bingo. DO NOT EDIT

go 1.15

require (
	github.com/bwplotka/bingo v0.2.3
	golang.org/x/mod v0.3.0 // indirect
	golang.org/x/xerrors v0.0.0-20200804184101-5ec99f83aff1 // indirect
)
