module _ // Auto generated by https://github.com/bwplotka/bingo. DO NOT EDIT

go 1.16

// TODO(bwplotka): Only go 1.14 is on Netlify image,
// so hugo can't be newer (it depends on io/fs from Go 1.16).

require github.com/gohugoio/hugo v0.80.0 // CGO_ENABLED=1 -tags=extended
