apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    prometheus: app-sre
  name: observatorium-thanos-receive
spec:
  endpoints:
  - port: http
  namespaceSelector:
    matchNames:
    - telemeter-production
  selector:
    matchLabels:
      app: thanos-receive
