apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    prometheus: app-sre
  name: observatorium-jaeger-agent-{{environment}}
spec:
  endpoints:
  - port: metrics
  namespaceSelector:
    matchNames:
    - '{{namespace}}'
  selector:
    matchLabels:
      app.kubernetes.io/name: jaeger-agent
