apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    prometheus: app-sre
  name: observatorium-thanos-receive-default
spec:
  endpoints:
  - port: http
  namespaceSelector:
    matchNames:
    - '{{namespace}}'
  selector:
    matchLabels:
      app.kubernetes.io/instance: default
      app.kubernetes.io/name: thanos-receive
