apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    prometheus: app-sre
  name: observatorium-thanos-store
spec:
  endpoints:
  - port: http
  namespaceSelector:
    matchNames:
    - telemeter-stage
  selector:
    matchLabels:
      app.kubernetes.io/name: thanos-store
